/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdvisorsRouteImport } from './routes/advisors'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FilmLocationsRouteImport } from './routes/film-locations'
import { Route as FounderRouteImport } from './routes/founder'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ListYourVenueRouteImport } from './routes/list-your-venue'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDeletionRequestsRouteImport } from './routes/_authenticated/deletion-requests'
import { Route as AuthenticatedLeadPageRouteImport } from './routes/_authenticated/lead-page'
import { Route as AuthenticatedPropertyCodesRouteImport } from './routes/_authenticated/property-codes'
import { Route as AuthenticatedSubscriptionsRouteImport } from './routes/_authenticated/subscriptions'
import { Route as VenuesIndexRouteImport } from './routes/venues.index'
import { Route as VenuesSlugRouteImport } from './routes/venues.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorsRoute = AdvisorsRouteImport.update({
  id: '/advisors',
  path: '/advisors',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmLocationsRoute = FilmLocationsRouteImport.update({
  id: '/film-locations',
  path: '/film-locations',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderRoute = FounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ListYourVenueRoute = ListYourVenueRouteImport.update({
  id: '/list-your-venue',
  path: '/list-your-venue',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeletionRequestsRoute =
  AuthenticatedDeletionRequestsRouteImport.update({
    id: '/deletion-requests',
    path: '/deletion-requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeadPageRoute = AuthenticatedLeadPageRouteImport.update({
  id: '/lead-page',
  path: '/lead-page',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPropertyCodesRoute =
  AuthenticatedPropertyCodesRouteImport.update({
    id: '/property-codes',
    path: '/property-codes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubscriptionsRoute =
  AuthenticatedSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const VenuesIndexRoute = VenuesIndexRouteImport.update({
  id: '/venues/',
  path: '/venues/',
  getParentRoute: () => rootRouteImport,
} as any)
const VenuesSlugRoute = VenuesSlugRouteImport.update({
  id: '/venues/$slug',
  path: '/venues/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisors': typeof AdvisorsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/film-locations': typeof FilmLocationsRoute
  '/founder': typeof FounderRoute
  '/gallery': typeof GalleryRoute
  '/list-your-venue': typeof ListYourVenueRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deletion-requests': typeof AuthenticatedDeletionRequestsRoute
  '/lead-page': typeof AuthenticatedLeadPageRoute
  '/property-codes': typeof AuthenticatedPropertyCodesRoute
  '/subscriptions': typeof AuthenticatedSubscriptionsRoute
  '/venues/$slug': typeof VenuesSlugRoute
  '/venues/': typeof VenuesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisors': typeof AdvisorsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/film-locations': typeof FilmLocationsRoute
  '/founder': typeof FounderRoute
  '/gallery': typeof GalleryRoute
  '/list-your-venue': typeof ListYourVenueRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deletion-requests': typeof AuthenticatedDeletionRequestsRoute
  '/lead-page': typeof AuthenticatedLeadPageRoute
  '/property-codes': typeof AuthenticatedPropertyCodesRoute
  '/subscriptions': typeof AuthenticatedSubscriptionsRoute
  '/venues/$slug': typeof VenuesSlugRoute
  '/venues': typeof VenuesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/advisors': typeof AdvisorsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/film-locations': typeof FilmLocationsRoute
  '/founder': typeof FounderRoute
  '/gallery': typeof GalleryRoute
  '/list-your-venue': typeof ListYourVenueRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/deletion-requests': typeof AuthenticatedDeletionRequestsRoute
  '/_authenticated/lead-page': typeof AuthenticatedLeadPageRoute
  '/_authenticated/property-codes': typeof AuthenticatedPropertyCodesRoute
  '/_authenticated/subscriptions': typeof AuthenticatedSubscriptionsRoute
  '/venues/$slug': typeof VenuesSlugRoute
  '/venues/': typeof VenuesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/advisors'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/film-locations'
    | '/founder'
    | '/gallery'
    | '/list-your-venue'
    | '/privacy'
    | '/refund-policy'
    | '/team'
    | '/terms'
    | '/admin'
    | '/dashboard'
    | '/deletion-requests'
    | '/lead-page'
    | '/property-codes'
    | '/subscriptions'
    | '/venues/$slug'
    | '/venues/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/advisors'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/film-locations'
    | '/founder'
    | '/gallery'
    | '/list-your-venue'
    | '/privacy'
    | '/refund-policy'
    | '/team'
    | '/terms'
    | '/admin'
    | '/dashboard'
    | '/deletion-requests'
    | '/lead-page'
    | '/property-codes'
    | '/subscriptions'
    | '/venues/$slug'
    | '/venues'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/advisors'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/film-locations'
    | '/founder'
    | '/gallery'
    | '/list-your-venue'
    | '/privacy'
    | '/refund-policy'
    | '/team'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/deletion-requests'
    | '/_authenticated/lead-page'
    | '/_authenticated/property-codes'
    | '/_authenticated/subscriptions'
    | '/venues/$slug'
    | '/venues/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdvisorsRoute: typeof AdvisorsRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  FilmLocationsRoute: typeof FilmLocationsRoute
  FounderRoute: typeof FounderRoute
  GalleryRoute: typeof GalleryRoute
  ListYourVenueRoute: typeof ListYourVenueRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  TeamRoute: typeof TeamRoute
  TermsRoute: typeof TermsRoute
  VenuesSlugRoute: typeof VenuesSlugRoute
  VenuesIndexRoute: typeof VenuesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisors': {
      id: '/advisors'
      path: '/advisors'
      fullPath: '/advisors'
      preLoaderRoute: typeof AdvisorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/film-locations': {
      id: '/film-locations'
      path: '/film-locations'
      fullPath: '/film-locations'
      preLoaderRoute: typeof FilmLocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder': {
      id: '/founder'
      path: '/founder'
      fullPath: '/founder'
      preLoaderRoute: typeof FounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list-your-venue': {
      id: '/list-your-venue'
      path: '/list-your-venue'
      fullPath: '/list-your-venue'
      preLoaderRoute: typeof ListYourVenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deletion-requests': {
      id: '/_authenticated/deletion-requests'
      path: '/deletion-requests'
      fullPath: '/deletion-requests'
      preLoaderRoute: typeof AuthenticatedDeletionRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lead-page': {
      id: '/_authenticated/lead-page'
      path: '/lead-page'
      fullPath: '/lead-page'
      preLoaderRoute: typeof AuthenticatedLeadPageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/property-codes': {
      id: '/_authenticated/property-codes'
      path: '/property-codes'
      fullPath: '/property-codes'
      preLoaderRoute: typeof AuthenticatedPropertyCodesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subscriptions': {
      id: '/_authenticated/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof AuthenticatedSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/venues/': {
      id: '/venues/'
      path: '/venues'
      fullPath: '/venues/'
      preLoaderRoute: typeof VenuesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venues/$slug': {
      id: '/venues/$slug'
      path: '/venues/$slug'
      fullPath: '/venues/$slug'
      preLoaderRoute: typeof VenuesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDeletionRequestsRoute: typeof AuthenticatedDeletionRequestsRoute
  AuthenticatedLeadPageRoute: typeof AuthenticatedLeadPageRoute
  AuthenticatedPropertyCodesRoute: typeof AuthenticatedPropertyCodesRoute
  AuthenticatedSubscriptionsRoute: typeof AuthenticatedSubscriptionsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDeletionRequestsRoute: AuthenticatedDeletionRequestsRoute,
  AuthenticatedLeadPageRoute: AuthenticatedLeadPageRoute,
  AuthenticatedPropertyCodesRoute: AuthenticatedPropertyCodesRoute,
  AuthenticatedSubscriptionsRoute: AuthenticatedSubscriptionsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AdvisorsRoute: AdvisorsRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  FilmLocationsRoute: FilmLocationsRoute,
  FounderRoute: FounderRoute,
  GalleryRoute: GalleryRoute,
  ListYourVenueRoute: ListYourVenueRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  TeamRoute: TeamRoute,
  TermsRoute: TermsRoute,
  VenuesSlugRoute: VenuesSlugRoute,
  VenuesIndexRoute: VenuesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
