/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FilmLocationsRouteImport } from './routes/film-locations'
import { Route as FounderRouteImport } from './routes/founder'
import { Route as ListYourVenueRouteImport } from './routes/list-your-venue'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as VenuesIndexRouteImport } from './routes/venues.index'
import { Route as VenuesSlugRouteImport } from './routes/venues.$slug'
import { Route as AuthenticatedInvoicePaymentIdRouteImport } from './routes/_authenticated/invoice.$paymentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmLocationsRoute = FilmLocationsRouteImport.update({
  id: '/film-locations',
  path: '/film-locations',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderRoute = FounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const ListYourVenueRoute = ListYourVenueRouteImport.update({
  id: '/list-your-venue',
  path: '/list-your-venue',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const VenuesIndexRoute = VenuesIndexRouteImport.update({
  id: '/venues/',
  path: '/venues/',
  getParentRoute: () => rootRouteImport,
} as any)
const VenuesSlugRoute = VenuesSlugRouteImport.update({
  id: '/venues/$slug',
  path: '/venues/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedInvoicePaymentIdRoute =
  AuthenticatedInvoicePaymentIdRouteImport.update({
    id: '/invoice/$paymentId',
    path: '/invoice/$paymentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/film-locations': typeof FilmLocationsRoute
  '/founder': typeof FounderRoute
  '/list-your-venue': typeof ListYourVenueRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/venues/$slug': typeof VenuesSlugRoute
  '/venues/': typeof VenuesIndexRoute
  '/invoice/$paymentId': typeof AuthenticatedInvoicePaymentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/film-locations': typeof FilmLocationsRoute
  '/founder': typeof FounderRoute
  '/list-your-venue': typeof ListYourVenueRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/venues/$slug': typeof VenuesSlugRoute
  '/venues': typeof VenuesIndexRoute
  '/invoice/$paymentId': typeof AuthenticatedInvoicePaymentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/film-locations': typeof FilmLocationsRoute
  '/founder': typeof FounderRoute
  '/list-your-venue': typeof ListYourVenueRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/venues/$slug': typeof VenuesSlugRoute
  '/venues/': typeof VenuesIndexRoute
  '/_authenticated/invoice/$paymentId': typeof AuthenticatedInvoicePaymentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/film-locations'
    | '/founder'
    | '/list-your-venue'
    | '/privacy'
    | '/refund-policy'
    | '/terms'
    | '/admin'
    | '/dashboard'
    | '/venues/$slug'
    | '/venues/'
    | '/invoice/$paymentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/film-locations'
    | '/founder'
    | '/list-your-venue'
    | '/privacy'
    | '/refund-policy'
    | '/terms'
    | '/admin'
    | '/dashboard'
    | '/venues/$slug'
    | '/venues'
    | '/invoice/$paymentId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/film-locations'
    | '/founder'
    | '/list-your-venue'
    | '/privacy'
    | '/refund-policy'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/venues/$slug'
    | '/venues/'
    | '/_authenticated/invoice/$paymentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  FilmLocationsRoute: typeof FilmLocationsRoute
  FounderRoute: typeof FounderRoute
  ListYourVenueRoute: typeof ListYourVenueRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  TermsRoute: typeof TermsRoute
  VenuesSlugRoute: typeof VenuesSlugRoute
  VenuesIndexRoute: typeof VenuesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/film-locations': {
      id: '/film-locations'
      path: '/film-locations'
      fullPath: '/film-locations'
      preLoaderRoute: typeof FilmLocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder': {
      id: '/founder'
      path: '/founder'
      fullPath: '/founder'
      preLoaderRoute: typeof FounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list-your-venue': {
      id: '/list-your-venue'
      path: '/list-your-venue'
      fullPath: '/list-your-venue'
      preLoaderRoute: typeof ListYourVenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/venues/': {
      id: '/venues/'
      path: '/venues'
      fullPath: '/venues/'
      preLoaderRoute: typeof VenuesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venues/$slug': {
      id: '/venues/$slug'
      path: '/venues/$slug'
      fullPath: '/venues/$slug'
      preLoaderRoute: typeof VenuesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/invoice/$paymentId': {
      id: '/_authenticated/invoice/$paymentId'
      path: '/invoice/$paymentId'
      fullPath: '/invoice/$paymentId'
      preLoaderRoute: typeof AuthenticatedInvoicePaymentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInvoicePaymentIdRoute: typeof AuthenticatedInvoicePaymentIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInvoicePaymentIdRoute: AuthenticatedInvoicePaymentIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  FilmLocationsRoute: FilmLocationsRoute,
  FounderRoute: FounderRoute,
  ListYourVenueRoute: ListYourVenueRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  TermsRoute: TermsRoute,
  VenuesSlugRoute: VenuesSlugRoute,
  VenuesIndexRoute: VenuesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
